// @ts-check

/**
 * Sidebar configuration for the Knowledge Base.
 * Uses autogenerated items so docs are auto-discovered from subdirectories.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'SRE Runbooks',
      items: [{type: 'autogenerated', dirName: 'sre-runbooks'}],
      link: {type: 'generated-index', description: 'Step-by-step SRE runbooks for incident response and reliability.'},
    },
    {
      type: 'category',
      label: 'Observability with Prometheus/Grafana',
      items: [{type: 'autogenerated', dirName: 'observability'}],
      link: {type: 'generated-index', description: 'Guides on monitoring, alerting, and dashboards with Prometheus and Grafana.'},
    },
    {
      type: 'category',
      label: 'Playwright Automation',
      items: [{type: 'autogenerated', dirName: 'playwright-automation'}],
      link: {type: 'generated-index', description: 'Playwright test automation patterns and best practices.'},
    },
    {
      type: 'category',
      label: 'AI in Testing',
      items: [{type: 'autogenerated', dirName: 'ai-in-testing'}],
      link: {type: 'generated-index', description: 'Exploring AI-driven testing approaches and tools.'},
    },
  ],
};

export default sidebars;
